[config]
filename=%date%-%time%.%ext%
author=%author%
series=%series%
source=E621
language=en
mode=comic
orientation=portrait
[e621]
#Both the username and api_key must be used to access the E621 API host so that this app can work.
#To set that up, go to: https://e621.net/api_keys/new and set a name, set the expiration for No Expiration. Click 'Create',
#then copy the key provided. Enter your accounts username and paste the key you generated into the api_key section.
username=
api_key=
timeout=10
client_name=E6PUB
client_version=1.0.0
